services:
  - type: web
    name: prim-bot2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot2.py
    envVars:
      - key: DISCORD_TOKEN2
        value: MTQ4ODIyNTMwODgwNDEyMDc1OQ.Gz_AVE.pwE3mgrsNOPhYqGR9C_L0ShDoLgLrlX5J3yUpA
    healthCheckPath: /health
